### ISSUE TITLE
Move from Coveralls to CodeCov.io

### ISSUE THREAD

**Issue by RichardLitt** [multiformats/js-multibase#11]
See https://github.com/ipfs/community/issues/219.

**Comment by diasdavid** [comment]
Let's avoid opening an issue in every repo and just track all of them in them in the main one (a la `awesome <endeavour>` we do in js-ipfs land

**Comment by RichardLitt** [comment]
Sounds good to me. We could also use project-repos to track it. Might be worth making an issue there saying 'greenlight coveralls switch', and then refer all PRs to that issue.
