### ISSUE TITLE
base32 is broken

### ISSUE THREAD

**Issue by dignifiedquire** [multiformats/js-multibase#17]
It seems base-x is not working as well as we thought it would. Probably other bases are broken as well

Todo: 

- Write more extensive tests
- Fix encoding

Failing example for base32

```js
const raw = new Buffer('1220120f6af601d46e10b2d2e11ed71c55d25f3042c22501e41d1246e7a1e9d3d8ec', 'hex')
const expected = 'bciqbed3k6ya5i3qqwljochwxdrk5exzqilbckapedujenz5b5hj5r3a'
const actual = 'bjcaeqpnl3advdoccznfyi624oflus7gbbmejib4qorerxhuhu5hwhm'
```

cc @diasdavid

**Comment by Kubuxu** [comment]
I would suggest importing test vectors from rfc4648, they might not cover this edge case but it won't hurt.

**Comment by diasdavid** [comment]
oh, this is unfortunate. Are we 100% positive that your example isn't the one that is broken?

**Comment by dignifiedquire** [comment]
@diasdavid yes I am sure both go-multibase and base32.js give the correct value
