### ISSUE TITLE
base64pad/base64urlpad not yet implemented

### ISSUE THREAD

**Issue by nmarley** [multiformats/js-multibase#19]
They are both included in the [multibase table](https://github.com/multiformats/multibase/blob/master/multibase.csv#L16) but these haven't yet been implemented in https://github.com/multiformats/js-multibase/blob/master/src/constants.js#L8

**Comment by diasdavid** [comment]
Thanks for noticing that, @nmarley. We haven't used it and neither the projects consuming this module which means we haven't had a driver to develop it.

We do accept PRs, let me know if you are interested in helping out :)

**Comment by nmarley** [comment]
Hey @diasdavid , sure, absolutely, would love to help. I started working on this in my fork w/a RFC 4648 test vector, but since it uses padding, it seems like it's not as trivial to implement as I originally thought.

**Comment by hacdias** [comment]
Nor base32pad!
