### ISSUE TITLE
get labels

### ISSUE THREAD

**Issue by diasdavid** [multiformats/js-multibase#2]
@RichardLitt could you run your script (or where can I find it?) to add labels on this repo?

**Comment by RichardLitt** [comment]
Sure. Is this the only repo? Or all of the multiformats?

**Comment by diasdavid** [comment]
all of the multiformats (I only had noticed this one :))

**Comment by RichardLitt** [comment]
Should be done. Added these labels. Reopen if you want more. 

```json
[
  {
    "name": "needs review",
    "color": "0052cc"
  },
  {
    "name": "difficulty:easy",
    "color": "bfe5bf"
  },
  {
    "name": "difficulty:moderate",
    "color": "bfe5bf"
  },
  {
    "name": "difficulty:hard",
    "color": "bfe5bf"
  }
]
```
