### ISSUE TITLE
Ambigous encoding due to underlying design

### ISSUE THREAD

**Issue by eth-r** [multiformats/js-multibase#24]
The truncation of leading zeros in the base-x package this library is built with creates an ambiguous encoding. This is especially noticeable in base-2 where the example test case `"yes mani !"` encodes to `"01111001011001010111001100100000011011010110000101101110011010010010000000100001"`, while a strict encoding would be `"001111001011001010111001100100000011011010110000101101110011010010010000000100001"`. This means that decoding `"\x00yes mani !"` results in `"yes mani !"`, an erroneous interpretation in many contexts.

More info: https://github.com/multiformats/multibase/issues/34

**Comment by vmx** [comment]
This is solved and is reflected in the test vectors.
