### ISSUE TITLE
typescript support

### ISSUE THREAD

**Issue by beenotung** [multiformats/js-multibase#29]
Please consider to officially include the typescript declaration file.
You can copy from my package: https://www.npmjs.com/package/typestub-multibase
repo: https://github.com/beenotung/typestub-multibase

**Comment by carsonfarmer** [comment]
I submitted https://github.com/DefinitelyTyped/DefinitelyTyped/pull/41416 for those interested. If @olizilla or any others are interested in having those types here, I'm happy to PR to this repo directly instead?

**Comment by carsonfarmer** [comment]
The types are now available: https://www.npmjs.com/package/@types/multibase
