### ISSUE TITLE
Use base-x

### ISSUE THREAD

**Issue by diasdavid** [multiformats/js-multibase#3]
Consider using https://www.npmjs.com/package/base-x

Verify if the base58 on that package is the btc or flickr versions

**Comment by theobat** [comment]
hi @diasdavid, it seems it can be any of each base's version since it takes the alphabet as an argument :
```javascript
var BASE58_BITCOIN = '123456789ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz'
var BASE58_FLICKR = '123456789abcdefghijkmnopqrstuvwxyzABCDEFGHJKLMNPQRSTUVWXYZ'
var BASE58_RIPPLE = 'rpshnaf39wBUDNEGHJKLM4PQRST7VWXYZ2bcdeCg65jkm8oFqi1tuvAxyz'
var bs58btc = require('base-x')(BASE58_BITCOIN)
var bs58flickr = require('base-x')(BASE58_FLICKR)
var bs58ripple = require('base-x')(BASE58_RIPPLE)
// encode-decode with the alphabet you'd like
```
So I guess we only have to map the alphabets to the constants in Constants.js ?

**Comment by diasdavid** [comment]
@theobat awesome! Yeah, seems like that then, constants.js can be the human readable name, the short version and the encoder/decoder instance. Would you like to contribute with PR adding this? Thank you!

**Comment by theobat** [comment]
@diasdavid Sure! I'll try to open a PR today, but I thought it could be nice to use an object-oriented declaration of the Bases such as jbenet mentioned [here](https://github.com/multiformats/go-multibase/issues/1). It won't be as useful as in Go but I think it would clarify the initialization. What do you think ?

Would be something like :
```javascript
const constants = {
  'base1': Base('1', '1'),
  'base2': Base('0', '01'),
  'base8': Base('7', '01234567'),
  // ... Base(code, alphabet) ... etc
}
```

**Comment by diasdavid** [comment]
@theobat thank you for this https://github.com/multiformats/js-multibase/pull/7 ❤️
