### ISSUE TITLE
Implement base36

### ISSUE THREAD

**Issue by hugomrdias** [multiformats/js-multibase#53]
https://github.com/multiformats/multibase/pull/65

refs:
https://github.com/multiformats/cid-utils-website/issues/23#issuecomment-633636760

**Comment by ribasushi** [comment]
@hugomrdias if of any help in js/wasm-land: https://github.com/multiformats/go-base36/blob/11f3b26a8e0e9068d38d6fa365d487dd00c6d057/base36.go
