### ISSUE TITLE
`web-encoding` package causes problems with jest in env=node and env=jsdom

### ISSUE THREAD

**Issue by moodysalem** [multiformats/js-multibase#66]
**Describe the bug**
When running the test in jest (with either env=jsdom or env=node setting) the `TextDecoder` or `TextEncoder` is not a constructor error makes it impossible to write unit tests using this module

**To Reproduce**
This simple test and code fails to run in jest
code:
https://github.com/Uniswap/uniswap-interface/blob/0aabf4856e6e90041caf4233db4b7defb01574a2/src/utils/contenthashToUri.ts
test:
https://github.com/Uniswap/uniswap-interface/blob/0aabf4856e6e90041caf4233db4b7defb01574a2/src/utils/contenthashToUri.test.skip.ts

error:
`TypeError: TextDecoder is not a constructor`
```  ● Test suite failed to run

    TypeError: TextDecoder is not a constructor

    > 1 | import CID from 'cids'
        | ^
      2 | import { getCodec, rmPrefix } from 'multicodec'
      3 | import { decode, toB58String } from 'multihashes'
      4 |

      at Object.<anonymous> (node_modules/multibase/src/util.js:6:21)
      at Object.<anonymous> (node_modules/multibase/src/base.js:4:24)
      at Object.<anonymous> (node_modules/multibase/src/constants.js:5:14)
      at Object.<anonymous> (node_modules/multibase/src/index.js:9:19)
      at Object.<anonymous> (node_modules/multihashes/src/index.js:10:19)
      at Object.<anonymous> (node_modules/cids/src/index.js:3:12)
      at Object.<anonymous> (src/utils/contenthashToUri.ts:1:1)
      at Object.<anonymous> (src/utils/contenthashToUri.test.ts:1:1)
```

**Expected behavior**
`TextDecoder` from the environment (specifically, global for node and window for jsdom jest setting) is successfully loaded

**Screenshots**
![image](https://user-images.githubusercontent.com/7897876/90529613-84770700-e139-11ea-9125-2a8cb611c17e.png)

**Desktop (please complete the following information):**
 - OS: MacOS

**Comment by moodysalem** [comment]
other issues: 
https://github.com/discordjs/discord.js/issues/3971#issuecomment-602010271

potential solution for us https://stackoverflow.com/a/57713960

**Comment by rvagg** [comment]
Going to suggest @Gozala is probably the one to take a look at this. If it's simple then it'd be great to fix. It seems that jsdom is just growing in use, not shrinking (which I wouldn't have expected!), so this might be fairly important.

**Comment by Gozala** [comment]
@moodysalem I'm not yet sure what is going on there yet, and sadly I have no experience with jest which does no help either. I am however guessing that problem here is that build picks up a wrong module, more specifically there are bunch entry points provided by web-encodings:

https://github.com/Gozala/web-encoding/blob/default/package.json#L10-L19

And I'm guessing that one being pulled in is (which assumes modern node >= 11.0.0 with ESM and [`TextEncoder` / `TextDecoder` globals](https://nodejs.org/dist/latest-v12.x/docs/api/globals.html#globals_textdecoder):

https://github.com/Gozala/web-encoding/blob/default/src/lib.js

Instead of the common JS module targeted for non ESM, which does pretty much what linked stackoverflow solution describes:
https://github.com/Gozala/web-encoding/blob/default/src/lib.cjs

@moodysalem what's the version of the node you're testing on ?

**Comment by Gozala** [comment]
And from stack trace it appears error is coming from https://github.com/multiformats/js-cid/blob/cbe44d41e19de9b5ae6de0607abf7027f84920af/src/index.js which no longer imports `TextDecoder` (directly).

**Comment by moodysalem** [comment]
> @moodysalem what's the version of the node you're testing on ?

Node v12.18.3, and same with CI, which both have `TextEncoder`/`TextDecoder` in the global NS

> And from stack trace it appears error is coming from https://github.com/multiformats/js-cid/blob/cbe44d41e19de9b5ae6de0607abf7027f84920af/src/index.js which no longer imports `TextDecoder` (directly).

The stack trace points at this line https://github.com/multiformats/js-multibase/blob/master/src/util.js#L6

**Comment by Gozala** [comment]
> > 
> 
> The stack trace points at this line https://github.com/multiformats/js-multibase/blob/master/src/util.js#L6

Oh right stack trace point to that, but code snippet seems to point to something else 😳

**Comment by Gozala** [comment]
Turns out problem is that react-scripts used by uniswap-interface uses old version of jest which does not recognize or support `.cjs` files. Unfortunately it does not appear to be a way to create a universal cjs / esm package without using `.cjs` files so we can't really work around this.

Good news is modern jest works without a problem and upcoming react-scripts also works (because it uses modern jest). With all that I think the best path forward would be to update to the upcoming `react-scripts`. If that is problematic, maybe work with react-scripts community to try an have minor release that just updates to new jest.

**Comment by Gozala** [comment]
It is also might be worth looking into why lib.cjs is been pulled in, in first place. I'd expect lib.js (ESM one) to be used given that it's imported from ESM:


https://github.com/multiformats/js-multibase/blob/424709195b46ffb1d6f2f69a7707598ebe751e5e/src/util.js#L4-L6

I'm guessing that has something to do with jest implementing their own custom module loader that did not recognized export maps (modern jest might do that).

**Comment by moodysalem** [comment]
Thank you for the investigation, I tried updating just the jest package to ^26.0.0 and the test errored in the same way. However I didn't upgrade any other dependencies, so the jest config would be the same.

**Comment by Gozala** [comment]
@moodysalem could you please try with new `teact-scripts` ? There could be more things going on there and would be good to confirm

**Comment by moodysalem** [comment]
with react-scripts `4.0.0-next.77` it fails with jsdom:

```
 FAIL  src/utils/contenthashToUri.test.ts
  ● Test suite failed to run

    ReferenceError: TextDecoder is not defined

      13 | }
      14 |
    > 15 | const UTF_8_DECODER = new TextDecoder()
         |                       ^
      16 |
      17 | /**
      18 |  * Returns the URI representation of the content hash for supported codecs

      at Object.<anonymous> (src/utils/contenthashToUri.ts:15:23)
      at Object.<anonymous> (src/utils/contenthashToUri.test.ts:1:1)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        0.711 s, estimated 1 s
Ran all test suites related to changed files.
```

and passes with env=node


```
 PASS  src/utils/contenthashToUri.test.ts
  #contenthashToUri
    ✓ 1inch.tokens.eth contenthash (3 ms)
    ✓ uniswap.eth contenthash
  #hexToUint8Array
    ✓ common case (1 ms)

Test Suites: 1 passed, 1 total
Tests:       3 passed, 3 total
Snapshots:   0 total
Time:        0.424 s
Ran all test suites related to changed files.
```

**Comment by Gozala** [comment]
I'll look into this more. I'm suspecting that it may be loading `lib.js` in there instead of `lib.cjs` which just assumes `TextDecoder` global, which is not available because jest swaps node global for jsdom window which does not have TextEncoder / TextDecoder.

**Comment by Gozala** [comment]
Relevant issue for JSDOM https://github.com/jsdom/jsdom/issues/2524

**Comment by Gozala** [comment]
@moodysalem what branch of the uniswap-interface are those changes on ? I would like to try figure it out, but I can't seem to find linked files in the master

**Comment by Gozala** [comment]
Never mind found it

**Comment by Gozala** [comment]
Also created jest issue https://github.com/facebook/jest/issues/10431

**Comment by Gozala** [comment]
@moodysalem as I started debugging I noticed that this time error is no longer coming from js-multibase or web-encoding packages it's coming from uniswap-interface itself:

https://github.com/Uniswap/uniswap-interface/blob/0aabf4856e6e90041caf4233db4b7defb01574a2/src/utils/contenthashToUri.ts#L15

**Comment by Gozala** [comment]
@moodysalem I have created https://github.com/Uniswap/uniswap-interface/pull/1056 to illustarte the fix.

I'm closing this issue, because there is noting we can do other than encourage react-scripts adopt nodes ESM support sooner.

**Comment by moodysalem** [comment]
Thanks @Gozala !
